export const API_ENDPOINTS = {
    projects: {
        list: '/projects',
        create: '/projects',
        get: (id: string) => `/projects/${id}`,
        update: (id: string) => `/projects/${id}`,
        delete: (id: string) => `/projects/${id}`,
    },
    auth: {
        login: '/auth/login',
        register: '/auth/register',
        logout: '/auth/logout',
        resetPassword: '/auth/reset-password',
        verifyEmail: '/auth/verify-email',
    },
    apiKeys: {
        list: '/api-keys',
        create: '/api-keys',
        get: (id: string) => `/api-keys/${id}`,
        revoke: (apiKeyId: string) => `/api-keys/${apiKeyId}/revoke`,
        rotate: (id: string) => `/api-keys/${id}/rotate`,
        getByProject: (projectId: string) => `/api-keys?projectId=${projectId}`,
    },
    testMetrics: {
        getMetricsById: (metricsId: string) => `/metrics/${metricsId}`,
        refreshMetrics: (metricsId: string) => `/metrics/${metricsId}/refresh`,
        deleteMetrics: (metricsId: string) => `/metrics/${metricsId}`,
        getProjectTestRunStats: (projectId: string) => `/projects/${projectId}/test-runs/stats`,
        getProjectTestSuiteStats: (projectId: string) => `/projects/${projectId}/test-suites/stats`,
    },
    testSuites: {
        get: (id: string) => `/test-suites/${id}`,
        update: (id: string) => `/test-suites/${id}`,
        complete: (id: string) => `/test-suites/${id}/complete`,
        delete: (id: string) => `/test-suites/${id}`,
    },
    testCases: {
        get: (id: string) => `/test-cases/${id}`,
        update: (id: string) => `/test-cases/${id}`,
        complete: (id: string) => `/test-cases/${id}/complete`,
        delete: (id: string) => `/test-cases/${id}`,
    },
    testRuns: {
        get: (id: string) => `/test-runs/${id}`,
        getByRunId: (runId: string) => `/test-runs/run/${runId}`,
        getByProjectId: (projectId: string) => `/projects/${projectId}/test-runs`,
        update: (id: string) => `/test-runs/${id}`,
        complete: (id: string) => `/test-runs/${id}/complete`,
        delete: (id: string) => `/test-runs/${id}`,
    },
}